package net.adriantodt.apicursos.common.model

data class Course(
    // Autogenerated IDs
    val courseId: Long,
    val siteId: Long,

    val url: String, // Match URL. may be autogenerated by client JS
    val name: String,

    val shortDescription: String, // Used for cards

    // Image used in cards and Captive page
    val imgHash: String? = null,
    val imgExt: String? = null,

    // Content
    val contentType: ContentType? = null,
    val contentHash: String? = null,
    val contentExt: String? = null,

    val captivePageHtml: String? = null, // Captive page
    val contentPageHtml: String? = null, // Content page

    // Collect info
    val collectName: Boolean = false,
    val collectEmail: Boolean = false,
    val collectPhone: Boolean = false,
    val collectCity: Boolean = false,
    val collectState: Boolean = false,
    val collectCountry: Boolean = false

)